### ISSUE TITLE
Motion Detection Alert

### ISSUE THREAD

**Issue by DaveGut** [401Unauthorized/locam#6]
There appears to not be a way go get a motion detection alert into the application.  True?

**Comment by 401Unauthorized** [comment]
Hi @DaveGut, there are no event driven motion detection alerts. That only works in the official application as it requires an internet connection and interacting with Kasa cloud services (both of which are not part of this project).

That said, you could build a polling option using the `events(type, startTime, endTime)` which checks if there have been any motion events in a recent period of time and call a function if there are any results. Would that be a viable option?

The code below will loop every `delayInMilliseconds` (5 seconds in this example) and check for events within the last 5 seconds. If there were any motion events, it will call the `motionDetected()` function.

```
const Camera = require('locam');

const c = new Camera({
    auth: {
        username: process.env.USERNAME, 
        password: process.env.PASSWORD
    },
    camera: {
        ip: '10.0.0.2',
        port: 10443,
        name: 'Camera_Name'
    },
    logging: true
});

function motionDetected(){
    console.log("Motion Detected!");
}

const delayInMilliseconds = 5000;

setInterval(function() {
  c.send(c.Settings.events("get", Date.now() - delayInMilliseconds, Date.now())).then(d => {
      if d["smartlife.cam.ipcamera.vod"]["get_detect_zone_list"]["total_number"] > 0 {
          motionDetected();
      }
  }).catch(err => {
      console.error(error);
  });
}, delayInMilliseconds);

```

**Comment by DaveGut** [comment]
Great information.  Thanks for the clarification.

ADDED:  You can detect an activity has occurred using the get_sysinfo command on the lan (port 9999).  If the value last activity time has changed, then go to the vod command to see what has changed.

BTW: I am starting with the Cloud implementation and will then transfer to the LAN when I have a useful integration.  I am also flushing out the other methods in the lexicon that you do not currently cover (there are a few that I do the equivalent on the other Kasa devices (LAN integration on Hubitat).  I will try to resolve as many of the below preambles as possible (from a Konsumer post):

smartlife.cam.ipcamera.audio
smartlife.cam.ipcamera.battery
smartlife.cam.ipcamera.siren
smartlife.cam.ipcamera.switch
smartlife.cam.ipcamera.cloud
smartlife.cam.ipcamera.dateTime
smartlife.cam.ipcamera.dayNight
smartlife.cam.ipcamera.debug
smartlife.cam.ipcamera.delivery
smartlife.cam.ipcamera.dndSchedule
smartlife.cam.ipcamera.intelligence
smartlife.cam.ipcamera.led
smartlife.cam.ipcamera.motionDetect
smartlife.cam.ipcamera.ptz
smartlife.cam.ipcamera.relay
smartlife.cam.ipcamera.rtp
smartlife.cam.ipcamera.camSchedule
smartlife.cam.ipcamera.sdCard
smartlife.cam.ipcamera.soundDetect
system
smartlife.cam.ipcamera.system
smartlife.cam.ipcamera.upgrade
smartlife.cam.ipcamera.videoControl
smartlife.cam.ipcamera.vod
smartlife.cam.ipcamera.wireless
