### ISSUE TITLE
Getting Error Code -10007, Unauthorized Error

### ISSUE THREAD

**Issue by DaveGut** [401Unauthorized/locam#7]
Loaded your code and then created the below test script.  I validated the username and password by logging out and back into the Kasa App.  I did not change any of the source modules.  Node JS Version:  16.14.2.

TEST CODE:
const Camera = require('locam');
const c = new Camera({
    auth: {
        username: 'xxxxxxxxx@outlook.com', 
        password: 'xxxxxxx'
    },
    camera: {
        ip: '0.0.50.43',
        port: 10443,
        name: 'camera'
    },
    logging: true
});
// Get Night Vision Setting
c.send(c.Settings.nightVision('get')).then(d => {
    console.log(d);
}).catch(err => {
    console.error(error);
});

Results: 
Configuration: {
  ip: 'xxxxxxx',
  port: 10443,
  name: 'camera',
  source: '8a2d067d-07fa-49b9-9289-d9f694f709b4',
  token: 'yyyyyyyyyyyyy',
  package: 'locam',
  version: '1.0.3'
}
{
  context: { source: { err_code: -10007, err_msg: 'Unauthorized Error' } },
  'smartlife.cam.ipcamera.dayNight': { get_mode: { err_code: -10007, err_msg: 'Unauthorized Error' } }
}

**Comment by 401Unauthorized** [comment]
Hi @DaveGut,

Thanks for providing that information, I'll take a look and see if I can replicate this issue.

**Questions**
1. Can you provide the model of the camera?
2. Can you provide the version and build of the Kasa app (Menu -> About)?
3. Can you try with changing the port to `9999` and see if you get the same results?

**Notes**
1. As the error is coming as a response from the camera the IP address set in the config must be correct.
2. You validated the username and password in the app so those must be correct.

**Comment by DaveGut** [comment]
Thanks for looking.  
Model: KC115(US)
Kasa App: 2.37.1 Build 1054 (android)
Changing to 9999 times-out the communications with associated error.

I am working on a port to Hubitat (where I already have control for all Kasa IOT devices except the Camera and wifi range-extender/switch).  Your integration was a good starting point and it is working through the cloud.  I am trying to expand using a list of kasa camera command names (I have to figure out the method from the name, not an exact).

That being said, the LAN version is highly preferable; therefore, why I am working with your app.  I believe the error I see means the connection is working and the command is clear.  Just no authorization (token????).  I get the same token in groovy as I do when using your app; therefore, my confusion.


Dave

**Comment by 401Unauthorized** [comment]
I've got a similar camera to the KC115 (EC70), the same Kasa app configuration and I've switched to testing on Node v16.14.2.

I've got the example you provided working, added some minor changes for clarity. Can you run this and provide the output again?
```
const Camera = require('locam');

const c = new Camera({
    auth: {
        username: process.env.USERNAME,
        password: process.env.PASSWORD
    },
    camera: {
        ip: process.env.IP,
        port: 10443,
        name: 'camera'
    },
    logging: true
});

// Get Night Vision Setting
const command = c.Settings.nightVision('get');
console.log('Command:', JSON.stringify(command))

c.send(command).then(d => {
    console.log('Response:', d);
}).catch(err => {
    console.error('Error:', err);
});
```

```
{
  'smartlife.cam.ipcamera.dayNight': { get_mode: { value: 'auto', err_code: 0 } }
}
```

When I intentionally change the `process.env.USERNAME` or `process.env.PASSWORD` to be incorrect, I receive the following:
```
{
  'smartlife.cam.ipcamera.dayNight': { get_mode: { err_code: -10007, err_msg: 'Unauthorized Error' } }
}
```

In your example, you saw following which is different than the response I get as it has the `context` field is included:
```
{
context: { source: { err_code: -10007, err_msg: 'Unauthorized Error' } },
'smartlife.cam.ipcamera.dayNight': { get_mode: { err_code: -10007, err_msg: 'Unauthorized Error' } }
}
```

To confirm, in the example you provided, since the `token` is redacted, do you see a long Base64 string? It would look something like this: `QmFzZTY0IGVuY29kaW5nIGlzIHVzZWQgZm9yIGxvY2FtIA==`?

I'll keep looking this over but your thoughts are correct that the IP & Port are correct, the device is reachable on the LAN and the command appears to be correct.

**Comment by DaveGut** [comment]
Still getting the unauthorized error.  Token looks similar.

When I modify the password/name or even zero out both, I get the same error (different tokens) - so it is somewhere in the authorization chain.

"In your example, you saw following which is different than the response I get as it has the context field is included:" - That is probably because the context method is also unauthorized.


Question: Have you set up a local password in your camera????  I use my Kasa Cloud password and have not seen where I can change this (except in the command list I am playing with).

**Comment by DaveGut** [comment]
Of course, the other area for error is in the Context portion of the command.  The value of source is set in your data package lib/models/config as "8a2d067d-07fa-49b9-9289-d9f694f709b4".  This looks like a uuid.  Should it reflect my PC's uuid?

**Comment by 401Unauthorized** [comment]
Hi @DaveGut,

Following up on this to see if you were able to get it working or if you need further assistance?

Regarding your questions:
1. Yes the username and password should be identical to the ones you are using on the Kasa app, there is no local password. Could you could try to (temporarily) change your password to be simple? I'm beginning to think this may be related to your password as I only tested this with passwords that didn't have special characters (i.e. $@&#) in them.

2. The context is a random UUID I generated as it did not appear to represent anything nor did it seem to need to be unique. You can modify the code to use, `bff0d9f3-010e-4e83-ac7e-a5e30da9e14e`, and see if it works but I have no reason to believe it should.

If this issue persists after the above two changes, I'll try and get a KC115 model camera to test on and see if I can replicate the issue.

**Comment by DaveGut** [comment]
Password: is very simple.  no special characters.
UUID: understand.
Status:  I will continue troubleshooting on my end.  You may close as you wish.  If I find a specific fix, I will notify you.

THANKS for the asssistance.
dave

**Comment by 401Unauthorized** [comment]
I've gone ahead and ordered the KC115 model camera to see if I can replicate this issue with a similar setup. I'll provide an update next week and will keep this issue open for now.

**Comment by 401Unauthorized** [comment]
Unfortunately, I've been unable to reproduce this issue with the same camera you have.
Can you confirm your camera is on the latest firmware/the one listed below?

I've found similar projects to this that only pull the video stream from the camera. You could always test to see if you can get either of these working to confirm _local_ access to your camera is working. You can't rely on the Kasa App to know as it attempts connecting locally and then uses the cloud API as a backup.

JS: https://github.com/tombastianello/kasa-spot-stream
Python: https://github.com/evets11/kasa-camera-stream

The above JS project uses a nearly [identical scheme](https://github.com/tombastianello/kasa-spot-stream/blob/main/app/index.ts#L13) for authentication as **locam**, so if that works for you, then I would be quite perplexed.

### Versions
**Node:** 16.14.2
**Model:** KC115
**Hardware Version:** 3.0
**Firmware Version:** 2.3.11

### Test Code
```javascript
const Camera = require('locam');

const c = new Camera({
    auth: {
        username: process.env.USERNAME,
        password: process.env.PASSWORD
    },
    camera: {
        ip: process.env.IP,
        port: 10443,
        name: process.env.NAME
    },
    logging: true
});

// Get Power Setting
const command = c.Settings.power('get');

c.send(command).then(d => {
    console.log('Response:', d);
}).catch(err => {
    console.error('Error:', err);
});
```

### Console Output
```javascript
Configuration: {
    ip: '192.168.1.2',
    port: 10443,
    name: 'Kasa_Cam',
    source: '8a2d067d-07fa-49b9-9289-d9f694f709b4',
    token: '<base64_token>',
    package: 'locam',
    version: '1.0.2'
}

Response: {
   'smartlife.cam.ipcamera.switch': { get_is_enable: { value: 'on', err_code: 0 } }
}

```

**Comment by DaveGut** [comment]
Thanks for the research.  

My KC-115 Model KC115 (did a firmware check this AM (no change from current).

- HW Version: **2.0**
- Firmware Version: **2.3.6**

The differences may be the issue.

I will look more later this week.  I am currently emersed in a Samsung Appliance project.
