### ISSUE TITLE
LOCAM also supports KD110 DOORBELL

### ISSUE THREAD

**Issue by DaveGut** [401Unauthorized/locam#8]
The basic code; especially the credentials/login work with the KD110 Doorbell.  Of course, the PTZ commands do not work, but other commands do.  Recommending updating readme to so indicate.

Dave

PS: Just tested KC115 again.  Still can not get this to work with my HW Ver 2 KC115,  I think the key is the Ver 2 HW.

**Comment by DaveGut** [comment]
Found out how to make the HW Version 2 to work.  The creation of the credentials in your method encode the password then encode the password:encodedUsername.  The fix for the KC115 HW V 2 is to use a simpler username:password encoded to base 64 (the password is not pre-encoded).   Both methods work for the KD-110 Doorbell (interesting and makes development simpler.

**Comment by 401Unauthorized** [comment]
Hi @DaveGut,

Thank you for letting me know about the `KD110 Doorbell`. I agree it's good to add a section to the [README](https://github.com/401Unauthorized/locam/blob/main/README.md) with a list of devices which are known to work.

Interesting discovery with the HW Version 2! The [previous implementation](https://github.com/401Unauthorized/locam/blob/main/src/camera/index.js#L23-L26) was likely changed in newer version of the app / hardware, as the `username:password encoded` makes more sense in general.

For the sake of backwards compatibility, it would be good to add this as an option in `opts.auth` as like `version: 2` and then add a switch in the `generateToken` func for using either the existing or new code.

I'll try to get around to making the changes soon, but I appreciate any consideration to raise a PR with the changes.

**Comment by DaveGut** [comment]
Stephen, some notes:

I code in groovy on the Hubitat Environment platform.  When finished I will attribute your work in that final code.  So, I do not feel I can raise a PR with explicit fixes.

Credentials clarification (after further development):  Your credentials method works on the Doorbell (KD110, HW 4.0, current Firmware).  The simplified method mentioned works on BOTH the doorbell and my older-version camera (KC115, HW 2.0, FW 2.3.6).  I will probably do a test on device installation into Hubitat to determine which method to use.

Camera Models.  Your code is for a Pan, Tilt, Zoom camera.  User needs to be aware that 'smartlife.cam.ipcamera.ptz' commands will not work on a fixed camera.  Also (definitely), not all commands will work on all device HW/Firmware versions.

See next message for some explicit comments.
Dave

**Comment by DaveGut** [comment]
I did testing on both my Camera and Doorbell.  Comments below are relative to the Doorbell Functions.

- Not in your code (but incorporated in mine and may be useful):
     - cmdData:[smartlife.cam.ipcamera.ptz:[get_all_preset:[]]], 
     - respData:[smartlife.cam.ipcamera.ptz:[get_all_preset:[maximum:4, `preset_attr:[[index:1, name:Viewpoint 1, wait_time:60, api_srv_url:use1-api.tplinkra.com, path:/v1/ipc/storage/device/801A6B000BD8CE1633ADD8CD0D36F46E1DA00A4F/preview/Viewpoint1], [index:2, name:Viewpoint 2, <truncated>], [index:3, name:Viewpoint 3, <truncated>], [index:4, name:Viewpoint 4, <truncated>]], err_code:0]]]`
- 'smartlife.cam.ipcamera.ptz': { 'set_move': { 'direction': dir, 'speed': speed } }
     - Note: Directions up/down do not work. Return smartlife.cam.ipcamera.ptz:[set_move:[err_code:-41203, err_msg:  The parameter value error.]
- 'smartlife.cam.ipcamera.dndSchedule': { 'set_dnd_enable': { 'value': status } }
     - Note1: Does not work on my camera (HW VER 2)
          - respData:[smartlife.cam.ipcamera.dndSchedule:[err_code:-1, err_msg:module not support]]
     - Note2: Does work on doorbell.  Listed in return as "newFeature"
          - respData:[smartlife.cam.ipcamera.dndSchedule:[get_dnd_enable:[enable:false, new_feature:1, err_code:0]]]
     - QUESTION:  Works on your camera?  If so, I will integrate into the my camera driver with ability to ignore.
